### ISSUE TITLE
Skull reward appearance does not match the dropped rarity

### ISSUE THREAD

**Issue by idogadol** [Tobi-Mob/Skul.Mod#2]
The skull reward has the appearance of a unique skull, yet it dropped a common one instead.
I encountered this bug twice in a row, both times in the first part of the game (the forest).
![Skul_ZMB9iC4njM](https://user-images.githubusercontent.com/85123657/154236112-e7a098ac-5d62-42aa-8aaa-7c284db01772.png)
![Skul_mOjBLahMIO](https://user-images.githubusercontent.com/85123657/154236124-b6f3ca85-1f01-4ca3-a43d-ee06f00861b0.png)

**Comment by idogadol** [comment]
Update: The reverse just happened, a common skull pile spawned a unique skull.

**Comment by Tobi-Mob** [comment]
With this mod it works like this:
Chapter 1 -> only drops common skulls
Chapter 2 -> only drops rare skulls
Chapter 3 -> only drops Unique skulls
(and so on)

Problem is, I was unable make the skull piles appearance match the skull rarity they will drop.
The skull piles will always get a random look, even if the drop rarity is fixed by the current chapter.

Since the problem is only visually (and I am a bit lazy) I won't look into that myself.
**But** since this mod is actually used, I am currently working on making modifications easier for other people.

If somebody is motivated to look into this. This is how to get the rarity for the current chapter:
https://github.com/Tobi-Mob/Skul.Mod/blob/920df29574d0cce8f7198e8344b34af838f73c95/Skul.Mod/Patches/DropRatePatch.cs#L235-L259

Any spawned skull pile would need to be modified, according to the chapter rarity, to fix this.

**Comment by idogadol** [comment]
Thanks for the reply!
