### ISSUE TITLE
Can you make a version of the mod without some of its features?

### ISSUE THREAD

**Issue by idogadol** [Tobi-Mob/Skul.Mod#3]
I can't go back to playing this game without Turbo Button Mode after experiencing it,
but I'm also not enjoying some of the mod's features.

**_I'm enjoying:_**

- **TurboButtonMode** 
- **Item drops configurable to drop a higher quality item every N drops**
- **No broken gates will be spawned, if avoidable.**

**_I'm only partially enjoying:_**

**- Always spawn a Skull-Reward and a Item-Reward gate, if possible.**
I only have gold for healing, previously I would be able to afford several items and item rerolls in a shop with a good money build.
My playstyle was previously to go for skulls and if there is no skull gate, then gold if possible.
After using this mod, I see that going for items is just as good, however, it isn't possible to maximize inscriptions anymore,
I can't get Spirit King Oberon or any crazy modifiers without a large amount of Gold, so **I would like an option to toggle this.**

**_I'm not enjoying:_**

- **Skull drops scale with current chapter.**
It causes disappointment, looting a skull pile worthy of entering Khorne's realm and getting a common skull is saddening,
despite knowing that later skulls will be better.
Having an early stroke of luck and an advantage is part of a roguelike's charm.
- **Infinite DarkQuartz to unlock upgrades.**
I already unlocked every item, upgrade and demon king castle upgrade before installing the mod,
so this cheat feature doesn't bother me too much.
However, I enjoyed seeing the number of Dark Quartz go up as I played the game,
and having it fixed to 100,000 is no longer satisfying.

**I would greatly appreciate a way to play your mod without scaling skulls and infinite dark quartz, and possibly disabling always having an item reward gate.**

**Comment by Tobi-Mob** [comment]
I agree that most of this features come down to personal preference (expect the Turbo Attack.Playing without is total madness for my finger :) )

I had some time to put something together. It is not the best, but hopefully helps a lot: [Skul.Mod](https://github.com/Tobi-Mob/Skul.Mod/releases/tag/v1.0.0)

![image](https://user-images.githubusercontent.com/69400800/154794010-0571960d-f17d-4153-b266-5bd4781c591d.png)

F3 now toggles ALL Item/Skull modifications
F4 now toggles ALL Path/Gate modifications
F5 now gives some dark quartz if required and the infinite quartz stuff is removed

Since how the game and the mod works, the reward gates are calculated ahead of time (I think half a chapter or something like that)

So F4 has to be pressed in the Caste to take effect for the next chapter. 
This could be improved and it should be possible to only replace broken gates. But that would require some more time.

**Comment by idogadol** [comment]
Thank you very much!
